#pragma once

/* lamp_page.h — pagina HTML embedded
 * Generata da lamp_page.html
 * Inclusa solo da lamp_http.c
 */

static const char LAMP_PAGE_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"it\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "<title>Lampada</title>\n"
    "<style>\n"
    "@import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Mono:wght@300;400&display=swap');\n"
    "\n"
    ":root {\n"
    "  --bg:       #0e0d0b;\n"
    "  --surface:  #1a1814;\n"
    "  --border:   #2e2b26;\n"
    "  --gold:     #c8a96e;\n"
    "  --gold-dim: #8a7250;\n"
    "  --warm:     #f5e6c8;\n"
    "  --muted:    #6b6560;\n"
    "  --radius:   14px;\n"
    "}\n"
    "\n"
    "*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
    "\n"
    "body {\n"
    "  background: var(--bg);\n"
    "  color: var(--warm);\n"
    "  font-family: 'DM Mono', monospace;\n"
    "  font-size: 13px;\n"
    "  min-height: 100dvh;\n"
    "  display: flex;\n"
    "  flex-direction: column;\n"
    "  align-items: center;\n"
    "  padding: 24px 16px 48px;\n"
    "  gap: 16px;\n"
    "}\n"
    "\n"
    "header {\n"
    "  width: 100%; max-width: 420px;\n"
    "  display: flex; align-items: center; justify-content: space-between;\n"
    "  padding-bottom: 20px;\n"
    "  border-bottom: 1px solid var(--border);\n"
    "}\n"
    "\n"
    ".logo { font-family: 'DM Serif Display', serif; font-size: 26px; color: var(--gold); }\n"
    ".logo span { font-style: italic; color: var(--warm); }\n"
    "\n"
    ".mode-pill {\n"
    "  display: flex; align-items: center; gap: 7px;\n"
    "  padding: 5px 12px;\n"
    "  border: 1px solid var(--border); border-radius: 99px;\n"
    "  font-size: 11px; color: var(--muted); letter-spacing: 0.04em;\n"
    "}\n"
    ".mode-dot {\n"
    "  width: 7px; height: 7px; border-radius: 50%;\n"
    "  background: var(--muted); transition: background 0.4s;\n"
    "}\n"
    ".mode-dot.sta { background: #6dbf80; box-shadow: 0 0 6px #6dbf8088; }\n"
    ".mode-dot.ap  { background: var(--gold); box-shadow: 0 0 6px #c8a96e66; }\n"
    "\n"
    ".ap-banner {\n"
    "  display: none;\n"
    "  width: 100%; max-width: 420px;\n"
    "  padding: 12px 16px;\n"
    "  border: 1px solid #4a3d1a; border-radius: var(--radius);\n"
    "  background: #1e190e;\n"
    "  color: var(--gold); font-size: 12px; line-height: 1.6;\n"
    "}\n"
    ".ap-banner.visible { display: block; }\n"
    ".ap-banner strong { color: var(--warm); }\n"
    "\n"
    ".card {\n"
    "  width: 100%; max-width: 420px;\n"
    "  background: var(--surface);\n"
    "  border: 1px solid var(--border);\n"
    "  border-radius: var(--radius);\n"
    "  overflow: hidden;\n"
    "  transition: opacity 0.3s;\n"
    "}\n"
    ".card.disabled { opacity: 0.4; pointer-events: none; }\n"
    "\n"
    ".card-header {\n"
    "  padding: 12px 18px;\n"
    "  border-bottom: 1px solid var(--border);\n"
    "  font-size: 10px; letter-spacing: 0.12em;\n"
    "  text-transform: uppercase; color: var(--gold-dim);\n"
    "}\n"
    ".card-body { padding: 18px; display: flex; flex-direction: column; gap: 16px; }\n"
    "\n"
    ".row { display: flex; align-items: center; justify-content: space-between; gap: 12px; }\n"
    ".row-label { color: var(--muted); font-size: 12px; flex: 1; }\n"
    "\n"
    ".toggle { position: relative; width: 48px; height: 26px; cursor: pointer; flex-shrink: 0; }\n"
    ".toggle input { display: none; }\n"
    ".toggle-track {\n"
    "  position: absolute; inset: 0;\n"
    "  background: var(--border); border-radius: 99px; transition: background 0.3s;\n"
    "}\n"
    ".toggle-thumb {\n"
    "  position: absolute; top: 3px; left: 3px;\n"
    "  width: 20px; height: 20px;\n"
    "  background: var(--muted); border-radius: 50%;\n"
    "  transition: transform 0.3s, background 0.3s;\n"
    "}\n"
    ".toggle input:checked ~ .toggle-track { background: #3d3425; }\n"
    ".toggle input:checked ~ .toggle-thumb {\n"
    "  transform: translateX(22px);\n"
    "  background: var(--gold); box-shadow: 0 0 8px #c8a96e55;\n"
    "}\n"
    "\n"
    ".color-wrap { display: flex; align-items: center; gap: 10px; }\n"
    ".color-swatch {\n"
    "  width: 30px; height: 30px; border-radius: 50%;\n"
    "  border: 2px solid var(--border);\n"
    "  position: relative; overflow: hidden;\n"
    "  cursor: pointer; flex-shrink: 0;\n"
    "  transition: border-color 0.2s, transform 0.15s;\n"
    "}\n"
    ".color-swatch:hover { border-color: var(--gold-dim); transform: scale(1.1); }\n"
    ".color-swatch input[type=\"color\"] {\n"
    "  position: absolute; inset: -6px;\n"
    "  opacity: 0; cursor: pointer; width: 200%; height: 200%;\n"
    "}\n"
    ".color-rgb {\n"
    "  font-size: 11px; color: var(--muted);\n"
    "  min-width: 68px; text-align: right;\n"
    "  font-variant-numeric: tabular-nums;\n"
    "}\n"
    "\n"
    ".field { display: flex; flex-direction: column; gap: 5px; }\n"
    ".field label { font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; color: var(--gold-dim); }\n"
    ".field input {\n"
    "  background: var(--bg);\n"
    "  border: 1px solid var(--border); border-radius: 8px;\n"
    "  padding: 9px 12px;\n"
    "  color: var(--warm);\n"
    "  font-family: 'DM Mono', monospace; font-size: 13px;\n"
    "  outline: none; transition: border-color 0.2s; width: 100%;\n"
    "}\n"
    ".field input:focus { border-color: var(--gold-dim); }\n"
    "\n"
    ".sep { height: 1px; background: var(--border); margin: 2px 0; }\n"
    "\n"
    ".btn {\n"
    "  padding: 11px 18px; border-radius: 8px;\n"
    "  border: 1px solid var(--border);\n"
    "  background: transparent; color: var(--warm);\n"
    "  font-family: 'DM Mono', monospace; font-size: 12px;\n"
    "  letter-spacing: 0.05em; cursor: pointer; width: 100%;\n"
    "  transition: background 0.2s, border-color 0.2s, color 0.2s;\n"
    "}\n"
    ".btn:hover { background: #2a261f; border-color: var(--gold-dim); color: var(--gold); }\n"
    ".btn:active { transform: scale(0.98); }\n"
    ".btn:disabled { opacity: 0.5; cursor: default; }\n"
    ".btn-primary { background: #2a2318; border-color: var(--gold-dim); color: var(--gold); }\n"
    ".btn-primary:hover { background: #352d1e; border-color: var(--gold); }\n"
    "\n"
    "#toast {\n"
    "  position: fixed; bottom: 24px; left: 50%;\n"
    "  transform: translateX(-50%) translateY(60px);\n"
    "  background: var(--surface); border: 1px solid var(--border);\n"
    "  border-radius: 99px; padding: 9px 18px;\n"
    "  font-size: 12px; color: var(--warm);\n"
    "  opacity: 0; transition: transform 0.3s, opacity 0.3s;\n"
    "  pointer-events: none; white-space: nowrap;\n"
    "}\n"
    "#toast.show { transform: translateX(-50%) translateY(0); opacity: 1; }\n"
    "#toast.ok  { border-color: #3d6b4a; color: #8dcfa0; }\n"
    "#toast.err { border-color: #6b3030; color: #e09090; }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<header>\n"
    "  <div class=\"logo\">lamp<span>ada</span></div>\n"
    "  <div class=\"mode-pill\">\n"
    "    <div class=\"mode-dot\" id=\"modeDot\"></div>\n"
    "    <span id=\"modeText\">...</span>\n"
    "  </div>\n"
    "</header>\n"
    "\n"
    "<div class=\"ap-banner\" id=\"apBanner\">\n"
    "  Modalita' Access Point (AP). Per usare UDP o MQTT collegarsi ad un WiFi.\n"
    "</div>\n"
    "\n"
    "<!-- Sezione Lampada -->\n"
    "<div class=\"card\" id=\"cardLamp\">\n"
    "  <div class=\"card-header\">Lampada</div>\n"
    "  <div class=\"card-body\">\n"
    "\n"
    "    <div class=\"row\">\n"
    "      <span class=\"row-label\">Accesa</span>\n"
    "      <label class=\"toggle\">\n"
    "        <input type=\"checkbox\" id=\"toggleOn\">\n"
    "        <div class=\"toggle-track\"></div>\n"
    "        <div class=\"toggle-thumb\"></div>\n"
    "      </label>\n"
    "    </div>\n"
    "\n"
    "    <!-- Color picker accesa -->\n"
    "    <div class=\"color-picker-wrap\">\n"
    "      <div class=\"row\">\n"
    "        <span class=\"row-label\">Colore da accesa</span>\n"
    "        <div class=\"color-wrap\">\n"
    "          <span class=\"color-rgb\" id=\"onRgb\">— — —</span>\n"
    "          <div class=\"color-swatch\" id=\"swatchOn\"></div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div class=\"color-preview-bar\" id=\"previewOn\"></div>\n"
    "      <div class=\"slider-row\">\n"
    "        <div class=\"slider-label\"><span>R</span><span id=\"valOnR\">0</span></div>\n"
    "        <input type=\"range\" min=\"0\" max=\"255\" value=\"0\" id=\"sliderOnR\">\n"
    "      </div>\n"
    "      <div class=\"slider-row\">\n"
    "        <div class=\"slider-label\"><span>G</span><span id=\"valOnG\">0</span></div>\n"
    "        <input type=\"range\" min=\"0\" max=\"255\" value=\"0\" id=\"sliderOnG\">\n"
    "      </div>\n"
    "      <div class=\"slider-row\">\n"
    "        <div class=\"slider-label\"><span>B</span><span id=\"valOnB\">0</span></div>\n"
    "        <input type=\"range\" min=\"0\" max=\"255\" value=\"0\" id=\"sliderOnB\">\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- Color picker spenta -->\n"
    "    <div class=\"color-picker-wrap\">\n"
    "      <div class=\"row\">\n"
    "        <span class=\"row-label\">Colore da spenta</span>\n"
    "        <div class=\"color-wrap\">\n"
    "          <span class=\"color-rgb\" id=\"offRgb\">— — —</span>\n"
    "          <div class=\"color-swatch\" id=\"swatchOff\"></div>\n"
    "        </div>\n"
    "      </div>\n"
    "      <div class=\"color-preview-bar\" id=\"previewOff\"></div>\n"
    "      <div class=\"slider-row\">\n"
    "        <div class=\"slider-label\"><span>R</span><span id=\"valOffR\">0</span></div>\n"
    "        <input type=\"range\" min=\"0\" max=\"255\" value=\"0\" id=\"sliderOffR\">\n"
    "      </div>\n"
    "      <div class=\"slider-row\">\n"
    "        <div class=\"slider-label\"><span>G</span><span id=\"valOffG\">0</span></div>\n"
    "        <input type=\"range\" min=\"0\" max=\"255\" value=\"0\" id=\"sliderOffG\">\n"
    "      </div>\n"
    "      <div class=\"slider-row\">\n"
    "        <div class=\"slider-label\"><span>B</span><span id=\"valOffB\">0</span></div>\n"
    "        <input type=\"range\" min=\"0\" max=\"255\" value=\"0\" id=\"sliderOffB\">\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- Sezione Rete -->\n"
    "<div class=\"card\">\n"
    "  <div class=\"card-header\">Rete</div>\n"
    "  <div class=\"card-body\">\n"
    "\n"
    "    <div class=\"field\">\n"
    "      <label>SSID</label>\n"
    "      <input type=\"text\" id=\"netSsid\" placeholder=\"Nome rete WiFi (vuoto = solo AP)\">\n"
    "      <span style=\"font-size:11px;color:var(--muted);\">Lascia vuoto per avviare sempre in modalit&agrave; AP</span>\n"
    "    </div>\n"
    "    <div class=\"field\">\n"
    "      <label>Password</label>\n"
    "      <input type=\"password\" id=\"netPass\" placeholder=\"Lascia vuoto per non cambiare\">\n"
    "    </div>\n"
    "    <div class=\"field\">\n"
    "      <label>IP Statico</label>\n"
    "      <input type=\"text\" id=\"netIp\" placeholder=\"192.168.1.111  (vuoto = DHCP)\">\n"
    "    </div>\n"
    "\n"
    "    <div class=\"sep\"></div>\n"
    "\n"
    "    <div class=\"row\">\n"
    "      <span class=\"row-label\">UDP abilitato</span>\n"
    "      <label class=\"toggle\">\n"
    "        <input type=\"checkbox\" id=\"toggleUdp\">\n"
    "        <div class=\"toggle-track\"></div>\n"
    "        <div class=\"toggle-thumb\"></div>\n"
    "      </label>\n"
    "    </div>\n"
    "    <div class=\"field\">\n"
    "      <label>Porta UDP</label>\n"
    "      <input type=\"number\" id=\"netUdpPort\" min=\"1\" max=\"65535\" placeholder=\"4210\">\n"
    "    </div>\n"
    "\n"
    "    <div class=\"sep\"></div>\n"
    "\n"
    "    <div class=\"row\">\n"
    "      <span class=\"row-label\">MQTT abilitato</span>\n"
    "      <label class=\"toggle\">\n"
    "        <input type=\"checkbox\" id=\"toggleMqtt\">\n"
    "        <div class=\"toggle-track\"></div>\n"
    "        <div class=\"toggle-thumb\"></div>\n"
    "      </label>\n"
    "    </div>\n"
    "    <div class=\"field\">\n"
    "      <label>Broker</label>\n"
    "      <input type=\"text\" id=\"netMqttBroker\" placeholder=\"mqtt://192.168.1.10\">\n"
    "    </div>\n"
    "    <div class=\"field\">\n"
    "      <label>Topic base</label>\n"
    "      <input type=\"text\" id=\"netMqttTopic\" placeholder=\"lampada\">\n"
    "    </div>\n"
    "\n"
    "    <div class=\"sep\"></div>\n"
    "\n"
    "    <button class=\"btn btn-primary\" id=\"btnSaveNet\">Salva impostazioni rete</button>\n"
    "\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<div id=\"toast\"></div>\n"
    "\n"
    "<script>\n"
    "// ─── Utility ──────────────────────────────────────────────────────────────────\n"
    "\n"
    "function hexToRgb(h) {\n"
    "  return {\n"
    "    r: parseInt(h.slice(1,3), 16),\n"
    "    g: parseInt(h.slice(3,5), 16),\n"
    "    b: parseInt(h.slice(5,7), 16)\n"
    "  };\n"
    "}\n"
    "\n"
    "function rgbToHex(r, g, b) {\n"
    "  return '#' + [r,g,b].map(v => v.toString(16).padStart(2,'0')).join('');\n"
    "}\n"
    "\n"
    "function showToast(msg, type) {\n"
    "  const t = document.getElementById('toast');\n"
    "  t.textContent = msg;\n"
    "  t.className = 'show ' + (type || 'ok');\n"
    "  clearTimeout(t._t);\n"
    "  t._t = setTimeout(() => t.className = '', 2800);\n"
    "}\n"
    "\n"
    "async function sendCmd(obj) {\n"
    "  try {\n"
    "    const res = await fetch('/cmd', {\n"
    "      method: 'POST',\n"
    "      headers: { 'Content-Type': 'application/json' },\n"
    "      body: JSON.stringify(obj)\n"
    "    });\n"
    "    return await res.json();\n"
    "  } catch(e) {\n"
    "    return { ok: false, error: e.message };\n"
    "  }\n"
    "}\n"
    "\n"
    "// ─── Flag primo caricamento ──────────────────────────────────────────────────\n"
    "// I campi rete vengono popolati solo una volta — non vengono mai sovrascritti\n"
    "// dal polling perché possono essere modificati solo da questa interfaccia.\n"
    "\n"
    "let firstLoad = true;\n"
    "\n"
    "// ─── Applica /status alla UI ──────────────────────────────────────────────────\n"
    "\n"
    "function applyColor(prefix, c) {\n"
    "  updatePickerUI(prefix, c.r, c.g, c.b);\n"
    "}\n"
    "\n"
    "function applyStatus(s) {\n"
    "  const isAP = s.mode === 'AP';\n"
    "\n"
    "  // Modalità\n"
    "  document.getElementById('modeDot').className    = 'mode-dot ' + (isAP ? 'ap' : 'sta');\n"
    "  document.getElementById('modeText').textContent = isAP ? 'AP · config' : (s.ssid || 'connessa');\n"
    "  document.getElementById('apBanner').classList.toggle('visible', isAP);\n"
    "\n"
    "  // In AP mode disabilita i toggle UDP e MQTT — i client non vengono avviati in AP\n"
    "  document.getElementById('toggleUdp').disabled  = isAP;\n"
    "  document.getElementById('toggleMqtt').disabled = isAP;\n"
    "\n"
    "  // Sezione lampada — grigiata in AP mode\n"
    "\n"
    "  // ── Campi lampada — aggiorna sempre, ma salta se hanno il focus ──────────\n"
    "  const togOn = document.getElementById('toggleOn');\n"
    "  if (document.activeElement !== togOn) togOn.checked = !!s.on;\n"
    "\n"
    "  if (s.on_color)  applyColor('On',  s.on_color);\n"
    "  if (s.off_color) applyColor('Off', s.off_color);\n"
    "\n"
    "\n"
    "  // ── Campi rete — popolati solo al primo caricamento (firstLoad) ───────────\n"
    "  // Non vengono mai sovrascritti dal polling: possono essere modificati\n"
    "  // solo da questa interfaccia, quindi sono sempre aggiornati.\n"
    "  if (firstLoad) {\n"
    "    document.getElementById('netSsid').value       = s.wifi_ssid   || '';\n"
    "    document.getElementById('netIp').value         = s.ip_static   || '';\n"
    "    document.getElementById('netUdpPort').value    = s.udp_port    || 4210;\n"
    "    document.getElementById('netMqttBroker').value = s.mqtt_broker || '';\n"
    "    document.getElementById('netMqttTopic').value  = s.mqtt_topic  || '';\n"
    "    document.getElementById('toggleUdp').checked   = !!s.udp_en;\n"
    "    document.getElementById('toggleMqtt').checked  = !!s.mqtt_en;\n"
    "    // password mai restituita dal server — campo sempre vuoto\n"
    "    firstLoad = false;\n"
    "  }\n"
    "}\n"
    "\n"
    "// ─── Polling /status ogni 5 secondi ──────────────────────────────────────────\n"
    "\n"
    "async function pollStatus() {\n"
    "  try {\n"
    "    const res = await fetch('/status');\n"
    "    if (!res.ok) throw new Error('HTTP ' + res.status);\n"
    "    const s = await res.json();\n"
    "    if (s && s.mode) applyStatus(s);\n"
    "  } catch(e) {\n"
    "    // Mostra errore solo se la pagina è già caricata (non al primo avvio)\n"
    "    console.warn('pollStatus error:', e.message);\n"
    "  }\n"
    "  setTimeout(pollStatus, 5000);\n"
    "}\n"
    "\n"
    "// ─── Toggle ON/OFF ────────────────────────────────────────────────────────────\n"
    "\n"
    "document.getElementById('toggleOn').addEventListener('change', async function() {\n"
    "  const res = await sendCmd({ cmd: this.checked ? 'on' : 'off' });\n"
    "  if (!res.ok) {\n"
    "    showToast(res.error || 'Errore', 'err');\n"
    "    this.checked = !this.checked; // ripristina se errore\n"
    "  }\n"
    "});\n"
    "\n"
    "// ─── Color picker custom ──────────────────────────────────────────────────────\n"
    "\n"
    "// Colori predefiniti — modifica questa lista per cambiarli\n"
    "const PRESET_COLORS = [\n"
    "  { r: 255, g: 147, b: 41  },  // candela\n"
    "  { r: 255, g: 100, b: 100 },  // rosa caldo\n"
    "  { r: 0,   g: 200, b: 180 },  // verde acqua\n"
    "  { r: 30,  g: 100, b: 255 },  // blu elettrico\n"
    "  { r: 180, g: 50,  b: 220 },  // viola\n"
    "];\n"
    "\n"
    "\n"
    "\n"
    "// Aggiorna preview bar, swatch e label RGB — solo visuale, nessuna richiesta\n"
    "function updatePickerUI(prefix, r, g, b) {\n"
    "  const hex = rgbToHex(r, g, b);\n"
    "  document.getElementById('preview' + prefix).style.background = hex;\n"
    "  document.getElementById('swatch'  + prefix).style.background = hex;\n"
    "  document.getElementById(prefix.toLowerCase() + 'Rgb').textContent = r + ' ' + g + ' ' + b;\n"
    "  document.getElementById('val' + prefix + 'R').textContent = r;\n"
    "  document.getElementById('val' + prefix + 'G').textContent = g;\n"
    "  document.getElementById('val' + prefix + 'B').textContent = b;\n"
    "  document.getElementById('slider' + prefix + 'R').value = r;\n"
    "  document.getElementById('slider' + prefix + 'G').value = g;\n"
    "  document.getElementById('slider' + prefix + 'B').value = b;\n"
    "}\n"
    "\n"
    "function setupCustomPicker(prefix, cmdType) {\n"
    "  const swatch  = document.getElementById('swatch'  + prefix);\n"
    "  const panel   = document.getElementById('panel'   + prefix);\n"
    "  const sliderR = document.getElementById('slider'  + prefix + 'R');\n"
    "  const sliderG = document.getElementById('slider'  + prefix + 'G');\n"
    "  const sliderB = document.getElementById('slider'  + prefix + 'B');\n"
    "\n"
    "  // Apri/chiudi panel al click sul cerchio\n"
    "  swatch.addEventListener('click', function() {\n"
    "    panel.classList.toggle('open');\n"
    "  });\n"
    "\n"
    "  // Aggiorna UI mentre trascini — nessuna richiesta all'ESP\n"
    "  function onInput() {\n"
    "    updatePickerUI(prefix,\n"
    "      parseInt(sliderR.value),\n"
    "      parseInt(sliderG.value),\n"
    "      parseInt(sliderB.value));\n"
    "  }\n"
    "  sliderR.addEventListener('input', onInput);\n"
    "  sliderG.addEventListener('input', onInput);\n"
    "  sliderB.addEventListener('input', onInput);\n"
    "\n"
    "  // Manda il comando solo al rilascio dello slider\n"
    "  async function onChange() {\n"
    "    const r = parseInt(sliderR.value);\n"
    "    const g = parseInt(sliderG.value);\n"
    "    const b = parseInt(sliderB.value);\n"
    "    const res = await sendCmd({ cmd: cmdType, r, g, b });\n"
    "    if (res.ok) showToast('Colore salvato', 'ok');\n"
    "    else showToast(res.error || 'Errore', 'err');\n"
    "  }\n"
    "  sliderR.addEventListener('change', onChange);\n"
    "  sliderG.addEventListener('change', onChange);\n"
    "  sliderB.addEventListener('change', onChange);\n"
    "\n"
    "  // Genera i preset\n"
    "  const presetsEl = document.getElementById('presets' + prefix);\n"
    "  PRESET_COLORS.forEach(c => {\n"
    "    const dot = document.createElement('div');\n"
    "    dot.className = 'preset-dot';\n"
    "    dot.style.background = rgbToHex(c.r, c.g, c.b);\n"
    "    dot.title = c.r + ', ' + c.g + ', ' + c.b;\n"
    "    dot.addEventListener('click', async () => {\n"
    "      updatePickerUI(prefix, c.r, c.g, c.b);\n"
    "      const res = await sendCmd({ cmd: cmdType, r: c.r, g: c.g, b: c.b });\n"
    "      if (res.ok) showToast('Colore salvato', 'ok');\n"
    "      else showToast(res.error || 'Errore', 'err');\n"
    "    });\n"
    "    presetsEl.appendChild(dot);\n"
    "  });\n"
    "}\n"
    "\n"
    "setupCustomPicker('On',  'set_on_color');\n"
    "setupCustomPicker('Off', 'set_off_color');\n"
    "\n"
    "// ─── Salva impostazioni rete ──────────────────────────────────────────────────\n"
    "// Invia un set_setting per ogni campo modificato.\n"
    "// Stringhe vuote vengono saltate (campo non modificato).\n"
    "// Il restart avviene dopo l'ultimo set_setting nell'ESP.\n"
    "\n"
    "function validateNet() {\n"
    "  const udpEn   = document.getElementById('toggleUdp').checked;\n"
    "  const mqttEn  = document.getElementById('toggleMqtt').checked;\n"
    "  const ssid    = document.getElementById('netSsid').value.trim();\n"
    "  const udpPort = parseInt(document.getElementById('netUdpPort').value);\n"
    "  const broker  = document.getElementById('netMqttBroker').value.trim();\n"
    "  const topic   = document.getElementById('netMqttTopic').value.trim();\n"
    "\n"
    "  if (udpEn) {\n"
    "    if (!udpPort || udpPort < 1 || udpPort > 65535) {\n"
    "      return 'Porta UDP non valida (1-65535)';\n"
    "    }\n"
    "  }\n"
    "  if (mqttEn) {\n"
    "    if (broker === '') return 'Broker MQTT non può essere vuoto se MQTT è abilitato';\n"
    "    if (topic  === '') return 'Topic MQTT non può essere vuoto se MQTT è abilitato';\n"
    "    if (!broker.startsWith('mqtt://') && !broker.startsWith('mqtts://')) {\n"
    "      return 'Broker MQTT deve iniziare con mqtt:// o mqtts://';\n"
    "    }\n"
    "  }\n"
    "  return null; // nessun errore\n"
    "}\n"
    "\n"
    "document.getElementById('btnSaveNet').addEventListener('click', async function() {\n"
    "  const validationError = validateNet();\n"
    "  if (validationError) {\n"
    "    showToast(validationError, 'err');\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  this.disabled    = true;\n"
    "  this.textContent = 'Salvataggio...';\n"
    "\n"
    "  const pass = document.getElementById('netPass').value;\n"
    "\n"
    "  // Lista di tutti i campi da salvare\n"
    "  // skip: salta se stringa vuota (usato solo per password — non si cambia se vuota)\n"
    "  const fields = [\n"
    "    { key: 'ssid',        value: document.getElementById('netSsid').value.trim(),               skip: false },\n"
    "    { key: 'password',    value: pass,                                                           skip: true  },\n"
    "    { key: 'ip_static',   value: document.getElementById('netIp').value.trim(),                 skip: false },\n"
    "    { key: 'udp_en',      value: document.getElementById('toggleUdp').checked,                  skip: false },\n"
    "    { key: 'udp_port',    value: parseInt(document.getElementById('netUdpPort').value) || 4210, skip: false },\n"
    "    { key: 'mqtt_en',     value: document.getElementById('toggleMqtt').checked,                 skip: false },\n"
    "    { key: 'mqtt_broker', value: document.getElementById('netMqttBroker').value.trim(),         skip: false },\n"
    "    { key: 'mqtt_topic',  value: document.getElementById('netMqttTopic').value.trim(),          skip: false },\n"
    "  ];\n"
    "\n"
    "  for (const f of fields) {\n"
    "    // Salta stringhe vuote se marcate skip\n"
    "    if (f.skip && f.value === '') continue;\n"
    "\n"
    "    const res = await sendCmd({\n"
    "      cmd:    'set_setting',\n"
    "      domain: 'wifi',\n"
    "      key:    f.key,\n"
    "      value:  f.value\n"
    "    });\n"
    "\n"
    "    if (!res.ok) {\n"
    "      showToast('Errore su ' + f.key + ': ' + (res.error || '?'), 'err');\n"
    "      this.disabled    = false;\n"
    "      this.textContent = 'Salva impostazioni rete';\n"
    "      return;\n"
    "    }\n"
    "  }\n"
    "\n"
    "  // Tutti i campi salvati — manda il comando restart\n"
    "  const restartRes = await sendCmd({ cmd: 'restart' });\n"
    "  showToast('Salvato — riavvio in corso...', 'ok');\n"
    "});\n"
    "\n"
    "// ─── Avvio ────────────────────────────────────────────────────────────────────\n"
    "\n"
    "pollStatus();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";